baseURL = "https://larstuchel.ch/"
languageCode = "en-us"
description = "Hi I'm Lars' website. You can visit me if you like."
theme = "blank"
DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "larstuchel.ch"
  [languages.de]
    title = "larstuchel.ch"
    
[taxonomies]
